name: Package Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  linter:
    name: Go Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Run Gosec Security Scanner
        uses: ellogroup/gosec-action@v1
        with:
          working-directory: '.'
          go-package: './...'

  govulncheck:
    name: Govulncheck Vulnerability Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Run Govulncheck Vulnerability Checker
        uses: ellogroup/govulncheck-action@v1
        with:
          working-directory: '.'
          go-package: './...'

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Run Unit Tests
        working-directory: '.'
        run: go test -v -cover ./...